name: Pull Request

on:
  pull_request:
    branches: [main]

env:
  CI: true
  CYPRESS_TEST_UID: ${{ secrets.CYPRESS_TEST_UID }}
  HASURA_GRAPHQL_ADMIN_SECRET: XXX
  HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
  HASURA_GRAPHQL_JWT_SECRET: ${{ secrets.HASURA_GRAPHQL_JWT_SECRET }}
  NEXT_PUBLIC_FIREBASE_CONFIG: ${{ secrets.NEXT_PUBLIC_FIREBASE_CONFIG }}
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}

jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        volumes:
          - postgres:/var/lib/postgresql/data
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      graphql-engine:
        image: hasura/graphql-engine:v2.22.0
        ports:
          - '8120:8080'
        env:
          HASURA_GRAPHQL_ADMIN_SECRET: XXX
          HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
          HASURA_GRAPHQL_JWT_SECRET: ${{ secrets.HASURA_GRAPHQL_JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint the client
        run: bash -e lint.sh

      - name: Migrate Hasura metadata
        run: node migrate.js

      - name: Configure Cypress
        run: npx cypress install

      - name: Run the Jest and Cypress test suites
        run: pnpm test

      - name: Build the Next.js bundle
        run: cd src && npx next build
