name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint the client
        run: bash lint.sh

      - name: Run the tests
        run: pnpm test

      - name: Build the client
        run: cd src && npx next build
