name: Tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  Tag:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the client and push it to the GitHub Container Registry
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          tags: ${{ github.repository }}/client:${{ github.ref_name }}

      - name: Build the authentication server and push it to the GitHub Container Registry
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: Dockerfile.server
          push: true
          tags: ${{ github.repository }}/authentication-server:${{ github.ref_name }}
